services:
  - type: web
    name: incidentops-api
    env: node
    region: singapore
    plan: free
    rootDir: apps/api
    buildCommand: pnpm install && pnpm --filter api build
    startCommand: node apps/api/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: api
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: JWT_REFRESH_REMEMBER_EXPIRY
        value: 30d
